### PR TITLE
Focus new file name input

### LINKED ISSUE #999: The Create New File button should focus the input box
Test case:

1. Click Create New File button
2. Type "Hello.sol"

Expected:

Text goes into the input box

Actual: 

Nothing

### PR DESCRIPTION
**Pull request by bitpshr**
This PR focuses the new file name input when creating a new contract.

Focus input preview

Resolves #999

### CODE REVIEW

**Comment by frankcodin** [comment]
+1

**Comment by bitpshr** [comment]
Note: The CI failure appears unrelated; it's effecting all new pull request CI runs. It occurs when attempting to establish a websocket connection in the `SharedFolderExplorer` test:

```
Timed out while waiting for element <[data-path="localhost"]>
to be present for 100000 milliseconds
```

**Comment by fulldecent** [comment]
Looks great, thank you!

**Comment by yann300** [comment]
thanks for that @bitpshr , could you give a rebase please?

**Comment by bitpshr** [comment]
@yann300 let me know if you'd like me to clean up anything else. Thanks!

**Comment by ninabreznik** [comment]
Very nice. Thanks, @bitpshr!

@yann300 I rebased @bitpshr 's repo and made a PR to his branch. He will update this PR and I think we can merge it. It works fine.

**Comment by bitpshr** [comment]
Let me know if there's anything else I can clean up on this @yann300. Thanks in advance!

**Comment by yann300** [comment]
thanks for this!

**Pull request merged**
