### PR TITLE
update to debugger doc

### PR DESCRIPTION
**Pull request by ryestew**
fixes https://github.com/ethereum/remix-project/issues/36
fixes fixes https://github.com/ethereum/remix-project/issues/606

### CODE REVIEW

**Comment by ryestew** [comment]
do not merge yet

**Comment by ryestew** [comment]
Please check the description of the stack.  Maybe the paragraph on line 74 is not necessary.  
Also I need a better explanation of the middle button in the debugger's nav.

**Comment by yann300** [comment]
@ryestew you could perhaps just link to https://en.wikipedia.org/wiki/Stack_(abstract_data_type)

**Comment by yann300** [comment]
> Also I need a better explanation of the middle button in the debugger's nav.

when you are in a call and click on that button it should directly move the slider to the end of that call

**Comment by yann300** [comment]
but seems there's an issue with it

**Review by yann300 — APPROVED** [review]

**Pull request merged**
