### PR TITLE
Resolve truffle like import

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by foxundermoon** [comment]
why not merge to master?

**Comment by yann300** [comment]
I think there's a better way to handle it... I can switch to that one soon , I will create an issue

**Comment by itstehkman** [comment]
Hi @yann300, is this something that is already supported / will be supported soon? I've gotten this feedback about Remix is that it is hard to resolve contracts that come from npm install, such as openzeppelin-solidity. This small PR would be a big win for productivity!

**Comment by yann300** [comment]
this is already supported @itstehkman 
please try installing and run https://github.com/ethereum/remixd#share-a-folder

**Pull request closed without merging**
