### PR TITLE
completed Chinese translation of file_explore, compile, settings, plugin_manager module

### PR DESCRIPTION
**Pull request by drafish**
1. update solidity_editor translation
2. completed Chinese translation of file_explore, compile, settings, plugin_manager module
3. delete _build/gettext dir
4. update zh_CN .po file
5. add zh_CN .mo file

### CODE REVIEW

**Comment by drafish** [comment]
request a review @ryestew @Aniket-Engg

**Comment by drafish** [comment]
Review required @yann300 @Aniket-Engg @ioedeveloper @LianaHus @bunsenstraat @ryestew

**Comment by ryestew** [comment]
@drafish - we should have a response for you on Tuesday. Thank you.

**Review by ryestew — COMMENTED** [review]
@drafish Thank you for this PR.  Would it be possible to have a call or to discuss outside of github (like on email or another channel)?  I will send you an email.

**Comment by drafish** [comment]
I have uploaded file_explore and compile po file on crowdin. It seems that you will download the po file from crowdin in the future and then update the files in the repository. Should I close this PR? Also, I found that the po file on crowdin is not up to date, you guys better update it. @ryestew

**Pull request closed without merging**
