### PR TITLE
WIP add new (reserved) Solidity 0.5.0 keywords to syntax highlighting

### LINKED ISSUE #1359: Add new (reserved) Solidity 0.5.0 keywords to syntax highlighting
PR https://github.com/ethereum/remix-ide/pull/1333

@raphaelhuefner

### PR DESCRIPTION
**Pull request by raphaelhuefner**
This PR is somewhat unprompted by remix-ide itself, but by https://gitcoin.co/issue/ethereum/solidity/3637/473

Refs: https://github.com/ethereum/solidity/issues/3637
Refs: https://gitcoin.co/issue/ethereum/solidity/3637/473

Fixes #1359.

### CODE REVIEW

**Comment by raphaelhuefner** [comment]
Just cross-posting from https://gitter.im/ethereum/remix-dev :

Hello Remix Core Team, hello @yann300 @chriseth @ninabreznik ! TL;DR: You OK with me making the Solidity syntax highlighting in Remix's ACE into it's own npm package?

Background:

- It needs a good clean-up anyways, there is lots of cruft from copy'n'pasting the JS highlighter.
- That way other ACE projects could use it, too.
- I.e. I hopped on a Gitcoin bounty to add syntax highlighting for "the new keywords" of Solidity 0.5.0 and while trying to figure out which keywords exactly that actually would be, I noticed that src/app/editor/mode-solidity.js is still missing quite a few keywords even from 0.4.x and still has tons of JS related stuff going on. (Including defining itself as "ace/mode/javascript", for instance.)

**Comment by axic** [comment]
Should this be merged first or just deprecated by #1415 ?

**Comment by raphaelhuefner** [comment]
@axic This should be deprecated by #1415.

**Comment by raphaelhuefner** [comment]
I'm not sure how I would go about deprecating this, sorry! Could you please give me a hand? Thank you!

**Comment by raphaelhuefner** [comment]
I'm closing this because it is deprecated by #1415.

**Pull request closed without merging**
