### PR TITLE
Adjusted static analysis warning notification appearance

### PR DESCRIPTION
**Pull request by dominique934**
This clarifies the static analysis warning notification. 
In a small user study among Austrian students who used remix, we found that participants mistakenly thought that the static analysis warning notification in the compile tab would refer to the other warnings below. Moreover, they did not assume that they had to click on the notification (or change the tab) to view the actual static analysis warnings in the respective tab. Thus, the appearance, as well as the text of the notification is adjusted, and the appearance of the warning(s) in the static analysis tab is displayed in the same format as the notification.    
A more detailed description of the study is provided in the attached pdf. 

[study_report_warnings.pdf](https://github.com/ethereum/remix-ide/files/1987884/study_report_warnings.pdf)

### CODE REVIEW

**Comment by dominique934** [comment]
Accidentially committed wrong files

**Comment by yann300** [comment]
many thanks for that PR, we would really like to have more feedback like that one, could you join https://gitter.im/ethereum/remix-dev ? perhaps we could push more update like this one.
@ninabreznik @ryestew

**Comment by dominique934** [comment]
Thanks a lot for the invitation to the chat! I hope to be able to contribute more update like this based on the results of my master thesis.

Could you help me with resolving the failed browser-tests? I could not figure out why they are failing.

**Comment by yann300** [comment]
you also need to update https://github.com/ethereum/remix-ide/blob/master/test-browser/tests/staticanalysis.js#L48

**Comment by dominique934** [comment]
Sorry, I should have seen this. Thanks a lot for your help!

**Comment by yann300** [comment]
@ryestew could you check that one please too?

**Pull request closed without merging**
