### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by yann300**
- don't clear input after sending
- add api in terminal "getFile"
- improve UX run tab
- add info icon

### CODE REVIEW

**Comment by ryestew** [comment]
- On the runtab- how is i next to Environment different from ? next to the contract pulldown?  I think it should the ? without the circle is a bit clearer - fa-question and maybe at 13 or 14px.  If they are basically doing the same thing - adding a bit of info & context - then they should both be an "i".

- Were we getting some complaints about confusion between atAddress and deploy?  It does make it kind of conversational and more legible to have the "or".  I tried putting a line separating them instead of the "or" but it looked more distracting.  So lets try the "or".  Maybe add 13px of margin-top above the Deploy:

image

For not clearing the inputs - do users generally not want the inputs cleared after submitting?  I assumed clearing would be better - or is clearing better for methods in the contract and not clearing is better for the constructor?

**Comment by yann300** [comment]
> On the runtab- how is i next to Environment different from ? next to the contract pulldown? I think it should the ? without the circle is a bit clearer - fa-question and maybe at 13 or 14px. If they are basically doing the same thing - adding a bit of info & context - then they should both be an "i".

right ;)

**Comment by yann300** [comment]
> Were we getting some complaints about confusion between atAddress and deploy?

not really but we were discussing that point during a call a few weeks/month ago

**Comment by yann300** [comment]
> For not clearing the inputs - do users generally not want the inputs cleared after submitting? I assumed clearing would be better - or is clearing better for methods in the contract and not clearing is better for the constructor?

I think there's a bug filed from an user for that (can't find the issue though), and after having tried a bit last week function / constructor execution, i think that more convenient to not clear the input. The main reason is that you often need to test the same function and you need to be able to easily copy/paste the inputs.

I think the better would be to be able to have some sort of autocompletion e.g a way to easily retrieve the inputs, so not clearing is like a "work around" for now.

**Comment by ryestew** [comment]
Everything looks fine - except the i seems a bit big - probably it should not have the font-size specified - as I had suggested when it was a ?.    Its a very tiny detail though. We can proceed with or without this change.

**Comment by ryestew** [comment]
1 more comment - the spacing between the Deploy button and the or and then between the or and the AtAddress button is not the same.  The Ataddress needs to have a margin-top of 6px - I think.

**Pull request merged**
