### PR TITLE
Issue#1462: Terminal command autocomplete support

### PR DESCRIPTION
**Pull request by PaddyMc**

### CODE REVIEW

**Comment by yann300** [comment]
wow, that's look very nice ;)  looking forward to see this in master.
A tiny comment, perhaps `up`, `down` can be used to scroll up/down in the functions list.
@ryestew could you give a try?

**Comment by PaddyMc** [comment]
Thanks @yann300 , I'm glad you like it! Yeah, I feel the same, I didn't want to add it on the first iteration as the terminal command line already has that functionality. 

@ryestew Feel free to reach out if you have any questions!

**Comment by ryestew** [comment]
This is so useful!  Thanks!

**Comment by PaddyMc** [comment]
Awesome, happy to help out!

**Comment by ryestew** [comment]
@PaddyMc - it seems to be failing a test.  Please try rebasing to see if that will fix the problem.  Thanks

**Comment by PaddyMc** [comment]
@ryestew - I've been looking into this for awhile and I think I've reproduced the error on the circleci.

When I run:

1. `npm run downloadsolc_root`

2. `npm run serve` => in separate terminal

3. `npm-run-all -lpr selenium browsertest`

<hr/>

The tests mostly pass except for this:

`- Compiling (14.214s)`
`[browsertest]    Timed out while waiting for element <.instance:nth-of-type(2)> to be present for 10000 
 milliseconds.  - expected "found" but got: "not found"`
<b>/test-browser/tests/compiling.js:42:8</b>

and this:

`- SharedFolderExplorer (1m 40s)`
`[browsertest]    Timed out while waiting for element <[data-path="localhost"]> to be present for 100000 milliseconds.  - expected "visible" but got: "not found"`
<b>/test-browser/tests/sharedFolderExplorer.js:67:6</b>

<hr/>

But when I run the tests without:

2. `npm run serve`

The errors I get are identical to the errors in PR [ #1582](https://circleci.com/gh/ethereum/remix-ide/2234?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) which leads me to believe that there seems to be an error with the CI. The error, I believe, is the CI cannot find the application!

Also the errors in PR [ #1582](https://circleci.com/gh/ethereum/remix-ide/2234?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) are === the errors in PR [#1522](https://circleci.com/gh/ethereum/remix-ide/2183?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) so this also points to errors in the CI.

Specifically this file: <b>ci/browser_tests.sh</b>
Specifically this line 43: <b>npm run nightwatch_remote_chrome</b>

<hr/>

Feel free to me know if I'm completely off the mark!

I hope this helps & let me know how you would like to proceed. Sorry for the mega-message! :)

**Comment by yann300** [comment]
Could you try clearing the ci cache?
in https://github.com/ethereum/remix-ide/blob/master/.circleci/config.yml
change all the `dep-bundle-22-` to `dep-bundle-23-`
and all the `dep-bundle-17-` to `dep-bundle-18-`

**Comment by PaddyMc** [comment]
That worked @yann300 , thanks! Just fixed the merge conflicts, should be good to go after this, hopefully! :)

**Comment by ryestew** [comment]
Hi PaddyMc, 
I was going over the design of your PR.  I think its going to integrate better with the rest of Remix if instead of creating the z-level div above the terminal, that you directly write to the terminal.
And writing to the terminal should be split into 2 PRs:
1. Just write to the terminal the entire list of commands and descriptions.  Use the class and method EditorPanel.logHtmlMessage in editorPanel.  Put a list of commands wrapped inside a div with some styling of each element.
2. Make the name of the command clickable so that it is printed to the console and then it makes the containing div of the list disappear.

Do you think you can do both steps?  Let me know if you have questions.
Thanks so much!

**Comment by PaddyMc** [comment]
Hey @ryestew,

Yeah I can, my availability is pretty slim atm, I will hopefully be able to start this task at the weekend, is that ok?

**Comment by PaddyMc** [comment]
@ryestew I've reviewed the suggestions and below is my feedback. 

1. During the design phase I tried to follow this guide as best as possible => [autocomplete design principles](https://baymard.com/blog/autocomplete-design). If every command was written to the terminal, it may get a little messy and no other auto complete <b><i>I've seen</i></b> is designed that way. That doesn't mean it shouldn't be done this way, that's just my opinion. Also it would take time to redesign the popup and functionality. 

2. This feature is already there, you are able to click on the text and it will fill the command line with the suggestion and remove the auto complete popup, I will add `cursor : pointer;` to the css file to make this more intuitive.

I hope this is OK, this is ye're application so ye have the final say of course, this is just my opinion! Let me know your thoughts on how you would like to proceed?

**Comment by ryestew** [comment]
HI PaddyMc - thanks for that article.  And you bring up some good points too.
Your widget does more than autocomplete: 

- it lists and explains the commands - so its like remix.help ( so has much more info than a traditional auto-complete.
- it also has autocomplete - by hitting **tab**. ( but you have to know you can use the tab)
- it offers the user a place to click to select a command. 
- also it is different from a traditional auto-complete because the list appears not immediately next to the text you type - but a bit above in the terminal.

The problem is that the z-level floating above the terminal as you have currently designed it, is not clear enough.

My posting from a few days ago, I had proposed a solution - but it has the shortcoming that it is not so different from a command like **remix.help()**.

Here is another solution that is also not good - but it is clear.  If we put the info in a modal dialog window - it is very legible - but of course it is blocking out the entire tool and one cannot type in the console - so it kills the auto-complete part of your tool.

image

I'll have another response tomorrow about a way forward.

**Comment by PaddyMc** [comment]
@ryestew Awesome, you are completely correct! Looking forward to collaborating and helping to build this feature!

**Comment by ryestew** [comment]
@PaddyMc 
Here is a list and a mockup.  Let me know if you think this adjustment is workable or if it has some shortcomings.

Its basically an adaptation of the modal dialog that hovers above a specific part of the page - the terminal - so let's call it the "terminal modal"
- a title
- an X to close
- color from the styleguide ( so that it will also work in the dark mode)
- page numbers
- the entire modal is stuck to the top of the console window - but the contained elements are top aligned - I mean so if there were only 2 elements or 3rd element was shorter - there would be blank space at the bottom.
- the z level probably needs to be greater than 3 to get over the menu bar above the terminal.
- I have a black border around the whole thing - but maybe just a shadow or nothing is better.
- the terminal modal is not as wide as the terminal.
- all parts of the terminal modal have an opacity of 1 - I mean - nothing has an opacity of .8.  Basically there isn't a translucent curtain.

hinter

**Comment by PaddyMc** [comment]
@ryestew Apologies for the delayed response. I'll definitely set aside some time this week to complete this task!

This looks great! Sounds workable as well.

I've two other features I think would be nice to add if you agree,

<hr></hr>

1. Have the input split by whitespace and always check the last item in the array

     - To allow auto-complete for commands like: `var myContract = web3.eth.Contract(jsonInterface[, address][, options])`

<hr></hr>

2. Remove the buttons for the bottom of the auto complete popup, handle navigation though arrow keys

- The 'Enter' key would select the item from the popup and the current item the user is on would be highlighted, left and right arrow keys would switch pages

     - To allow much faster use of the popup 

<hr></hr>

Let me know your thoughts on these two additions?

Do you already have code written that I could expand upon or would you like me to start by porting the code I've written to a `modal-dialog-custom.js` file that extends `app/ui/modaldialog.js`?

**Comment by PaddyMc** [comment]
@ryestew Any update on this?

**Comment by ryestew** [comment]
HI PaddyMc - sorry about the delay, devcon and the birth of my son distracted me.  
As for your addition 

1. (addition 1) Yes! that would be a nice thing.  
2. (addition 2) - just a question - How do you think people would know to use the arrow keys? While the arrow icons are a little clunky - their use is self-evident.  Do you think we could use both - the arrow keys and the arrow icons?  

And I think it would easiest and safest to continue to update your files - src/app/ui/auto-complete-popup.js and the css file rather porting them over to modal-dialog-custom.js

**Comment by PaddyMc** [comment]
No problem at all @ryestew and congratulations! 

I'll have a bit of free time towards the end of the week to make the changes, I'll update you then.

**Comment by ryestew** [comment]
Great - thanks so much!

**Comment by PaddyMc** [comment]
@ryestew This is ready for review, whenever you have time!

**Comment by ryestew** [comment]
Hi PaddyMc - I'll review it before Tuesday - thanks!  I have a feeling that it will need another rebase.  But I'll let you know what I think shortly.

**Pull request closed without merging**
