### PR TITLE
Add plugin oneClickDapp

### PR DESCRIPTION
**Pull request by pi0neerpat**
Sup code surfers :surfing_man: 

I built a plugin for generating **persistent** interfaces directly from Remix. Hopefully this makes the development and education for smart contracts easier for all!

### CODE REVIEW

**Comment by yann300** [comment]
great, thanks for the PR ;)
https://github.com/pi0neerpat/remix-plugin-one-click-dapp/blob/master/src/index.ts#L2
instead of using require this, could you require `@remixProject/plugin`
import { createIframeClient } from '@remixproject/plugin';

**Comment by pi0neerpat** [comment]
Good call. Just updated this.

**Comment by yann300** [comment]
is that already deployed in your hosting?

**Comment by pi0neerpat** [comment]
yes, I just deployed here `remix-one-click-dapp.surge.sh`

**Pull request merged**
