### PR TITLE
Fix Docker run instructions in Readme

### PR DESCRIPTION
**Pull request by boxhock**
Easy fix for a small problem

### CODE REVIEW

**Comment by edisinovcic** [comment]
@boxhock did you manage to get this running?

As your proposed format is not working for me

```
docker run -p 8080:80 remixproject-remix-ide:latest
Unable to find image 'remixproject-remix-ide:latest' locally
docker: Error response from daemon: pull access denied for remixproject-remix-ide, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

And usually format of images when pulling from docker hub is repository/image:tag. (For example solc: https://hub.docker.com/repository/docker/ethereum/solc/tags?page=1)

**Comment by boxhock** [comment]
Hi @edisinovcic, I think you got that wrong.

The current readme has the format you just tried that fails.
My PR fixes this.

**Comment by edisinovcic** [comment]
Ah sorry, good catch :)

**Comment by yann300** [comment]
thanks @boxhock ;)

**Pull request merged**
