### PR TITLE
Terminal e2e tests

### PR DESCRIPTION
**Pull request by ioedeveloper**

### CODE REVIEW

**Comment by yann300** [comment]
this contains change in `test-browser/tests/gist.js` . should that stay in this PR?

**Comment by ioedeveloper** [comment]
I moved `importFromGist.js` tests into `gist.js` tests since they are all gist tests. I just thought i could include it in this PR since it a minor change but I can take it out of this PR and open a new PR for it if you are more comfortable with that.

**Comment by ioedeveloper** [comment]
Moreover, i still plan on updating this test with `data-attributes` once https://github.com/ethereum/remix-ide/pull/2591 is merged.

**Comment by yann300** [comment]
can that be merged?

**Comment by ioedeveloper** [comment]
Yes, it is ready to be merged, but it does not contain your recent changes in https://github.com/ethereum/remix-ide/pull/2605 . So, it is probably best that https://github.com/ethereum/remix-ide/pull/2605 be merged first and i update this PR with the changes.

**Pull request merged**
