### PR TITLE
Clean support tab content

### PR DESCRIPTION
**Pull request by yann300**
- move solidity version selector to compile tab
 - move remix, remixd info to support tab
 - refactor plugin loading/removing

### CODE REVIEW

**Comment by ninabreznik** [comment]
Feedback

**Support tab**
- run remix locally (does this belong to Remix or would we rather have this kind of info in the documentation?) Maybe we should make a text above the chat, where we link to documentation, more visible and a bit bigger. I think it would be better to have all the info that is not part of the app in one place and this is documentation.
- accessing local files (same as above and/OR where it belongs - in the module that appears when you click on RemixD icon.)

**Settings tab**
- styling in plugin box is broken. Buttons behave strange and text is not align in the center (is it using style guide styling we use for buttons?)
- when you click Oraclize, some React/Redux stuff logs in the console.
- refactoring plugin - what should be checked here, I couldn't figure it out.

**Compile tab**

- i think compile button is not so nicely visible now, so I would maybe move it inside of the box above so compiler selection and compile button are there together.

And then we can have details and other buttons in the next box. I will be working on fixing the compile tab a bit, so I can take over this part.

**Comment by yann300** [comment]
> I think it would be better to have all the info that is not part of the app in one place and this is documentation.

Right, the idea behind that (put the info in remix / settings directly) was to put these information in a place where user go frequently.

>styling in plugin box is broken. Buttons behave strange and text is not align in the center (is it using style guide styling we use for buttons?)

might be yes

> when you click Oraclize, some React/Redux stuff logs in the console.
that come from the Oraclize code, you can't do so much here

> refactoring plugin - what should be checked here, I couldn't figure it out.

nothing specific. just that now, when you paste a plugin description and click load, it add the plugin to the list of available plugin. before it would just start it, with no way of having a custom plugin in list.

> I will be working on fixing the compile tab a bit, so I can take over this part.

ok, linking the issue https://github.com/ethereum/remix-ide/issues/1227

**Comment by yann300** [comment]
thanks for the comment @ninabreznik 
I have dispatched everything in other thread / issues.

**Comment by yann300** [comment]
merging this, to be continued in next PRs

**Pull request merged**
