### PR TITLE
Display plugin as a Tab

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by yann300** [comment]
note that the wording `editorPanel` is not accurate anymore. will change that in subsequent PR

**Comment by GrandSchtroumpf** [comment]
If you :
1 - Search for a plugin
2 - Activate a plugin
Then the search is discarded. I would remain.

**Comment by yann300** [comment]
right, thanks
just added 2 more commits to it

**Comment by GrandSchtroumpf** [comment]
When clicking on `Run Tests` under `Unit Testing` I've got `self.compileTab.importFileCb is not a function`

**Comment by GrandSchtroumpf** [comment]
When using `Vyper` the solidity compiler tries to compile and fails.

**Comment by GrandSchtroumpf** [comment]
Pipeline should open on activation (not current behavior), but vyper should not (current behavior)

**Comment by GrandSchtroumpf** [comment]
When `ethdoc` is activated, an empty iframe pop at the bottom of the page. Maybe it should be `display: none` by default.

**Comment by GrandSchtroumpf** [comment]
When runTab becomes active, it doesn't check if there were a contract already compiled.

**Comment by yann300** [comment]
@GrandSchtroumpf added a new issue for listing all your feedback 
https://github.com/ethereum/remix-ide/issues/1705

**Comment by GrandSchtroumpf** [comment]
Ok, thanks

**Pull request merged**
