### PR TITLE
Compile tab ui

### PR DESCRIPTION
**Pull request by ninabreznik**
UI fixes in the Compile tab

screenshot_2018-08-24_02-28-24
screenshot_2018-08-24_02-28-08

### CODE REVIEW

**Comment by yann300** [comment]
Overall looks better!
some comments though:
 - There's a little glitch when the compiler loading icon switch from `idle` to `compiling`.
 - Isn't the Details button too large?
 - Was not really sure about changing the icon of `publish to Swarm` into this. At first sight that looks not really consistent with all the other actions... well would be great to have another point of view @ryestew

**Comment by ryestew** [comment]
I think the buttons should all be gray - if not they look like one button is in a down state ( well that is if 1 color is darker). So given that - here is what it looks like if the buttons are the same width. 
image

**Comment by ryestew** [comment]
But when the rt panel is a bit narrow the buttons need some help.
image

**Comment by ryestew** [comment]
Though this looks pretty good:
image

**Comment by ryestew** [comment]
Or take out the buttons for the copy icons because the icon already catchy like a button
image

**Comment by ryestew** [comment]
All of these choices minimizes the importance of "Publish to Swarm".  Publish to swarm is really cool even if not that many people currently use it.  When its an icon on the right it may be too understated.  Just a sec...

**Comment by ryestew** [comment]
If we make the pulldown a bit more narrow: 
 image

**Comment by ryestew** [comment]
Here's the whole panel:
image

**Comment by yann300** [comment]
Should the Swarm action have rounded border like for abi and bytecode?

**Comment by ryestew** [comment]
@yann300 - here's what it looks like for me - there is not button for swarm - just the icon.  But maybe I don't follow you:
image

**Pull request merged**
