### PR TITLE
Include git clone of ethereum/remix for dev instructions

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by ninabreznik** [comment]
Hey @axic, thanks for the PR. 

I think that this command already runs the clone, but maybe it would be nice to add in the parenthesis what exactly the command does. 

@yann300 ?

**Comment by axic** [comment]
Oh sorry, I just realised I didn't do `pullremix`, only `linkremixlib` because that was the one I needed to change.

It could be more clear tbh.

**Comment by ninabreznik** [comment]
I agree. If you wasn't sure, then it's obviously the problem we didn't communicate it clear enough. So thanks for the feedback. Will improve this one!

**Comment by axic** [comment]
Created an issue and closing this then.

**Pull request closed without merging**
