### PR TITLE
Bootstrap runtab aliscious

### PR DESCRIPTION
**Pull request by ryestew**

### CODE REVIEW

**Comment by ryestew** [comment]
Still to be done:
Maybe update the alert for a card 
and...

**Comment by yann300** [comment]
Could we close the topic run tab UX for now or are there some other changes to apply?

**Comment by ryestew** [comment]
A few small updates to this PR coming in a half hour.

**Comment by ryestew** [comment]
Last update to accommodate long input names in the multi-param manager ( the accordion to input 1 param at a time).  The deployed instance is still an alert - not a card - so it has a background color.  Maybe it should be a card.  Inside the multi-param-manager - the bg-color is light.

**Comment by ryestew** [comment]
this is associated with #1849

**Pull request merged**
